### ISSUE TITLE
Remove a link please

### ISSUE THREAD

**Issue by asanakoy** [shuaibingtao/pointcloud#1]
Him=,

Could you please remove the link to my pytorch repository
"[arXiv] Neural Point-Based Graphics. [pytorch] [project] [oth.]"
from the list?

This is a private code which was not meant to be exposed to public. I would very appreciate if you could just remove the link to the source code.

**Comment by shuaibingtao** [comment]
Hello, I uploaded the code of point cloud classification based on voxel pyramid written by myself in C++, which does not use pytorch. I wonder if it is the same as yours.But I can guarantee that this code is written by myself, and there is no important code uploaded by me. Please kindly confirm it carefully.

At 2019-09-23 17:44:27, "Artsiom" <notifications@github.com> wrote:


Him=,

Could you please remove the link to my pytorch repository
"[arXiv] Neural Point-Based Graphics. [pytorch] [project] [oth.]"
from the list?

This is a private code which was not meant to be exposed to public. I would very appreciate if you could just remove the link to the source code.

**Comment by asanakoy** [comment]
You misunderstood me. I talking about the `[pytorch]` link related to "Neural Point-Based Graphics" paper. 

Look at the screenshot please:
![image](https://user-images.githubusercontent.com/1690869/65423227-6e18dc00-de00-11e9-9ede-56d8b06fbdab.png)
